### ISSUE TITLE
Support Authentication Basic

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-OAI#12]
```
$ catmandu convert OAI --url http://myhost.edu  --user bla --password 
```

or

```
$ catmandu convert OAI --url http://myhost.edu  --credentials ~/oai.passwords
```

(Required for the Flemish VIAA project)

**Comment by nicolasfranck** [comment]
This is already supported, because it uses internally LWP as the user agent.
LWP::UserAgent accepts username and password as part of the URL:

catmandu convert OAI --url "http://username:password@myhost.edu"

**Comment by netsensei** [comment]
This doesn't work when the OAI endpoint is served through an IIS server with NTLM authentication.

NTLM authentication is an alternative to Basic Authentication. It's a protocol which was designed and developed by Microsoft to work in conjunction with Active Directory. NTML piggy backs on Basic Authentication but it actually requires a 4-way handshake before you can log in.

See: 
https://www.innovation.ch/personal/ronald/ntlm.html
https://msdn.microsoft.com/en-us/library/aa292114(v=vs.71).aspx (Integrated Windows Authentication)

LWP::UserAgent does support NTLM authentication:
http://search.cpan.org/dist/libwww-perl/lib/LWP/Authen/Ntlm.pm

HTTP::OAI::Harvester just extends LWP::UserAgent through HTTP::OAI::UserAgent. So, technically Catmandu::OAI should implement NTLM support as described in the previous link. 

Use case: Adlib (http://alm.axiell.com/solutions/technology/adlib) does provide an OAI endpoint through IIS, protected through NTLM.

At this point, I'm fiddling to get it to work with the Adlib instance I'm confronted with. Catmandu::OAI still just has to support standard Basic Auth too, so I can see a few design questions to be solved on the UI side, looming on the horizon (ie. do we want to provide credentials per @nicolasfranck or do we need to pass them thru a separate switch per @phochste)

**Comment by netsensei** [comment]
> At this point, I'm fiddling to get it to work with the Adlib instance I'm confronted with.

So. At this point, I can't get NTLM support in Catmandu::OAI working. I tried connecting with a separate script (http://www.perlmonks.org/bare/?node_id=835211) but I get an unintelligible error saying my credentials are invalid.

Maybe I should just go with plain basic auth over SSL. I know HMAC like auth is better, but without proper client support, that won't be really an option.

**Comment by nicolasfranck** [comment]
And I thought OAI meant "Open Archives Initiative" ;-).

I'll look into it.

**Comment by netsensei** [comment]
Got it working if I add $agent->credentials in OAI.pm :-)

**Comment by nicolasfranck** [comment]
Ok, kan you try the branch "credentials"?

Checkout branch  credentials to $HOME/Catmandu-OAI
```
cd $HOME
git clone https://github.com/LibreCat/Catmandu-OAI.git
git checkout -b credentials remotes/origin/credentials
```
Test
```
export PERL5LIB="$HOME/Catmandu-OAI/lib"
catmandu convert OAI --url "http://localhost/oai" --credentials host:port --credentials realm --credentials username --credentials password to YAML
```

In Getopt::Long this is the way to supply multiple values for the same parameter.
You need to supply ALL four credential values to make basic authentication succeed. The hardest part will be to find out
what the "realm" is called. In my case it was called "Realm" ;-)

Normally this should also work for NTLM authentication, but I'm not sure how many
values it requires for the parameter "credentials".

**Comment by netsensei** [comment]
Ok. This seems to work.

> what the "realm" is called. In my case it was called "Realm" ;-)

In my case, providing an empty realm works. Just passing `--credentials ''` seems to do the trick.

> Normally this should also work for NTLM authentication, but I'm not sure how many
values it requires for the parameter "credentials".

You need at least 3: host, username & password.  Username could be 'domain\\username' if it refers to a user registered in Active Directory.

The 'realm' parameter is optional.

I can see how this works. I can see a problem though. The order of the parameters passed to the CLI command is important to make it work.

This works: 
`catmandu convert OAI --url "http://localhost/oai" --credentials host:port --credentials realm --credentials username --credentials password to YAML`

This won't (switched the username and password params):
`catmandu convert OAI --url "http://localhost/oai" --credentials host:port --credentials realm --credentials password --credentials username  to YAML`

The only way to circumvent this is to heavily document this. And even then, this will create confusion for those that don't read documentation.

Apparently, there are different types of 'basic authentication':

* There's 'classic' basic authentication as we know it (run of the mill .htpasswd support in Apache)
* There's digest authentication
* NTLM
* Client Certificate mapping

(see: https://msdn.microsoft.com/en-us/library/aa292114(v=vs.71).aspx)

I was wondering if `$agent->credentials`  supports these each of these types too. Or at least 'regular' basic auth, digest auth & NTLM.  In that case, we should just expose the function argument list to the outside world:

`catmandu convert OAI --url "http://localhost/oai" --host host:port --realm realm --username username --password password to YAML`

Each argument should be optional. Meaning we don't need to validate the user input, because the OAI will do that for us. i.e. if the password param is missing and only the username is provided, then the OAI will respond with a 403.

If it's NTLM, then the 'host' should be passed to the command too, but it's up to the user to make sure the host is passed. Catmandu shouldn't be concerned / be aware whether or not NTLM authentication is being used to access the endpoint, nor should it validate if the host param is present if NTLM is used.

What do you think?

**Comment by netsensei** [comment]
Also, it's up to the OAI Data Provider to document & publish their own endpoint. If they put restrict access through NTLM or other schemes, it should be noted in the endpoint documentation. The harvester shouldn't have to guess / figure out which type of authentication is being used.

**Comment by phochste** [comment]
Can these new features please be documented before it is send to CPAN

**Comment by nicolasfranck** [comment]
Ok I just updated the branch. Now the options are:

  * realm
  * username
  * password

Host and port are no longer required, as they are parsed from the url:

```
catmandu convert OAI --url "https://lib.ugent.be/OAI" --username a --password b --realm oai to YAML
````

**Comment by netsensei** [comment]
Thanks! That seems to work.

Just submitted a pull request with 1 bugfix + pod documentation for the new options.
