### ISSUE TITLE
Normalize date format

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu-OAI#13]
Option from and until expect strict data format. Better allow strings like `YYYYMMDD`, `yesterday` etc. and let the module normalize.

**Comment by nicolasfranck** [comment]
mm, isn't it better to stay as close as possible to the API, instead of adding functionalities that only exist here? It isn't user friendly, I admit ,but it gives you direct access and error report, instead of indirect. 

If the input date string were to be reinterpreted, and a misinterpretation (by the library) happens, you will have a hard time debugging, trying to find out what was actually sent to the API.
