### ISSUE TITLE
resumptionToken Issue

### ISSUE THREAD

**Issue by lightonphiri** [LibreCat/Catmandu-OAI#24]
I have been frantically attempting to use the resumptionToken option in order to skip/avoid records that result in errors, when I attempt to harvest  records. However, the resumptionToken flag does not seem to work: I am not certain what it is I am doing wrong.

The code I am working with is below.

`catmandu convert OAI --url http://dspace.unza.zm:8080/oai/request --metadataPrefix oai_dc --handler oai_dc to CSV --fix 'join_field(_setSpec,"|")' --fix 'join_field(title,"|")' --fix 'join_field(creator, "|")' --fix 'join_field(subject,"|")' --fix 'join_field(description, "|")' --fix 'join(date, "|")' --fields _identifier,_datestamp,_setSpec,title, creator, subject, description, date --resumptionToken "oai_dc////1800"`

**Comment by phochste** [comment]
It works for me. The only issue I see is that you have spaces in the --fields list:

_identifier,_datestamp,_setSpec,title, creator, subject, description, date

instead of 

_identifier,_datestamp,_setSpec,title,creator,subject,description,date

The command line toolkit thinks they are new options.

I recommend to write these fields in double quotes:

--fields "_identifier,_datestamp,_setSpec,title,creator,subject,description,date"

And put all the fixes in a Fix script e.g. myfixes.fix:

join_field(_setSpec,"|")
join_field(title,"|")
join_field(creator, "|")
join_field(subject,"|")
join_field(description, "|")
join(date, "|")

The command is then:

catmandu convert OAI --url  http://dspace.unza.zm:8080/oai/request --resumptionToken "oai_dc////1800" to CSV --fix myfixes.fix --fields "_identifier,_datestamp,_setSpec,title,creator,subject,description,date"

**Comment by phochste** [comment]
It works for me. The only issue I see is that you have spaces in the --fields list:


_identifier,_datestamp,_setSpec,title, creator, subject, description, date


instead of


_identifier,_datestamp,_setSpec,title,creator,subject,description,date


The command line toolkit thinks they are new options.


I recommend to write these fields in double quotes:


--fields "_identifier,_datestamp,_setSpec,title,creator,subject,description,date"


And put all the fixes in a Fix script e.g. myfixes.fix:


join_field(_setSpec,"|")
join_field(title,"|")
join_field(creator, "|")
join_field(subject,"|")
join_field(description, "|")
join(date, "|")


The command is then:


catmandu convert OAI --url  http://dspace.unza.zm:8080/oai/request --resumptionToken "oai_dc////1800" to CSV --fix myfixes.fix --fields "_identifier,_datestamp,_setSpec,title,creator,subject,description,date"


BR,

Patrick


________________________________

**Comment by lightonphiri** [comment]
Aha! I see what I did wrong. Thank you so much for this.
