### ISSUE TITLE
Harden the OAI importer against bad data

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-OAI#7]
Importing large repositories over many hours is subject to all kinds of services downtimes, XML syntax errors, etc. To have any practical OAI harvest of large repositories the Catmandu::OAI importer should support options to harvest as many records as possible. The current importer can stop suddenly in the middle of an harvest without any indication what happend (did the server close the connection? was there a XML syntax error in one of the records?).

**Comment by danmichaelo** [comment]
Several different issues to handle here, but for network errors (connection timeout, DNS errors, etc.) and 5XX server errors (which are often temporary due to server load or other downtime), what do you think about introducing a small sleep before retrying using the last resumptionToken? Something like this PHP code:

https://github.com/scriptotek/php-oai-pmh-client/blob/master/src/Client.php#L158-L180

**Comment by nicolasfranck** [comment]
cf. https://github.com/LibreCat/Catmandu-OAI/pull/17
